version: '3.1'

services:

  db:
    container_name: postgres
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: user_backend
      POSTGRES_PASSWORD: user_backend
      POSTGRES_DB: user_backend
    ports:
      - "5432:5432"

  gui:
    container_name: pgadmin4
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: karol@karol.pl
      PGADMIN_DEFAULT_PASSWORD: admin