spring:
  jpa:
#    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: postgres
    url: "jdbc:postgresql://localhost:5432/user_backend"
    username: user_backend
    password: user_backend
#    driverClassName: org.postgresql.Driver
#    jpa:
##      generate-ddl: true
#      hibernate:
#        show_sql: true
#        ddl-auto: create
##        ddl-auto: create-drop
##        ddl-auto: none
